networks:
  internal:

services:
  web:
    build: .
    command: python app.py 
    ports:
      - target: 8080
        published: 5555
    networks:
      - internal
  store:
    image: "redis:alpine"
    networks:
      internal:
