networks:
  counter-net:

volumes:
  counter-vol:
  
services:
  web-fe:
   # build: .
    image: docker-init-web-fe:latest
   # command: python app.py 
    ports:
      - target: 8080
        published: 5005
    networks:
      - counter-net
    volumes:
      - type: volume
        source: counter-vol
        target: /app
  redis:
    image: "redis:alpine"
    networks:
      counter-net:
